name: soundflow_app
description: SoundFlow Main Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sf_core:
    path: ../../packages/sf_core
  sf_design_system:
    path: ../../packages/sf_design_system
  # Downgraded to 1.6.8 to avoid toARGB32() error in Flutter 3.24
  dynamic_color: 1.6.8
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
