name: sf_design_system
description: SoundFlow Design System (Material You 3+)
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Downgraded to 1.6.8 to avoid toARGB32() error in Flutter 3.24
  dynamic_color: 1.6.8
  google_fonts: ^6.2.1
